name = "libre-tv"
pages_build_output_dir = "."
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "my-tv-db"
database_id = "0d98d364-48b3-4947-88ab-694aef1c1163" # Local dev ignores this ID and uses local DB
